#!/usr/bin/env bash
mkdir System_engineering_and_Devops
mv * System_engineering_and_Devops
git remote remove origin
cd System_engineering_and_Devops
git init
git remote add origin ""
git pull origin master
cd ..
mkdir AirBnB_Clone_V2
cd AirBnB_Clone_V2
git init
git remote add origin ""
git pull origin master
cd ..
