#!/usr/bin/env bash
# 404 error

ERRORFILE="/usr/share/nginx/html/404error.html"
FOUR="Ceci n'est pas une page"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
FILE="/etc/nginx/sites-available/default"

echo "$FOUR" > "$ERRORFILE"
sed -i "37i\ $ERRORREDIRECT" "$FILE"

service nginx restart
