#!/usr/bin/env bash
# automate your fix.
ln -sf "/etc/nginx/sites-available/default" "/etc/nginx/sites-enabled/default"
service nginx restart
kill -9 $(ps -aux | grep "nginx: master process" | tr -s ' ' | cut -d ' ' -f 2)
