#!/usr/bin/env bash
# nginx user change
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i '/listen 80 default_server;/c\\tlisten 8080 default_server;' /etc/nginx/sites-available/default
sudo sed -i '/listen [::]:80 default_server ipv6only=on;/c\\tlisten [::]:8080 default_server ipv6only=on;' /etc/nginx/sites-available/default
sudo service nginx restart
