#!/usr/bin/env bash
# nginx user change
sudo pkill apache2
sudo chmod 744 /etc/nginx/nginx.conf
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i '/listen 80 default_server;/c\\tlisten 8080 default_server;' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
