#!/usr/bin/env bash
# nginx user change
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
